"""init

Revision ID: 1c4f35e7a08f
Revises: 7b030fab8d7e
Create Date: 2025-04-13 20:14:33.826872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4f35e7a08f'
down_revision: Union[str, None] = '7b030fab8d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mirea', sa.Column('is_active_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mirea', 'is_active_email')
    # ### end Alembic commands ###
