"""edit metrics

Revision ID: 7d38d42225e8
Revises: e000ae06ae59
Create Date: 2025-04-28 18:01:59.448249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d38d42225e8'
down_revision: Union[str, None] = 'e000ae06ae59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departament_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_count', sa.Integer(), nullable=True),
    sa.Column('departament_id', sa.Integer(), nullable=True),
    sa.Column('authors_count', sa.Integer(), nullable=True),
    sa.Column('k1_count', sa.Integer(), nullable=True),
    sa.Column('k2_count', sa.Integer(), nullable=True),
    sa.Column('k3_count', sa.Integer(), nullable=True),
    sa.Column('rinc_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['departament_id'], ['departament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employee_metrics', sa.Column('authors_count', sa.Integer(), nullable=True))
    op.add_column('employee_metrics', sa.Column('k1_count', sa.Integer(), nullable=True))
    op.add_column('employee_metrics', sa.Column('k2_count', sa.Integer(), nullable=True))
    op.add_column('employee_metrics', sa.Column('k3_count', sa.Integer(), nullable=True))
    op.add_column('employee_metrics', sa.Column('rinc_count', sa.Integer(), nullable=True))
    op.add_column('employee_metrics', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_metrics', 'message')
    op.drop_column('employee_metrics', 'rinc_count')
    op.drop_column('employee_metrics', 'k3_count')
    op.drop_column('employee_metrics', 'k2_count')
    op.drop_column('employee_metrics', 'k1_count')
    op.drop_column('employee_metrics', 'authors_count')
    op.drop_table('departament_metrics')
    # ### end Alembic commands ###
