"""add elibrary_id to user

Revision ID: dc09cf69e171
Revises: 5ee5582da9e0
Create Date: 2025-04-21 18:48:13.324756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc09cf69e171'
down_revision: Union[str, None] = '5ee5582da9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mirea', sa.Column('elibrary_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mirea', 'elibrary_id')
    # ### end Alembic commands ###
